oracle_install_group: oinstall
oracle_groups:
  - dba
  - oinstall
  - oper
  - asmdba
  - asmdba

root_user: root
oracle_user: oracle
grid_user: grid

oraclepasswd: oracle
gridpasswd: oracle

root_dir: /u02
stage_dir: /u02/stage
oracle_base: /u02/app

first_node: opsdev
ansible_hostname: opsdev

packages_list:
  - compat-libcap1
  - gcc
  - gcc-c++
  - glibc
  - glibc.i686
  - glibc-devel
  - glibc-devel.i686
  - ksh
  - libaio.i686
  - libaio-devel
  - libaio-devel.i686
  - libstdc++.i686
  - libstdc++-devel
  - libstdc++-devel.i686
  - libXi
  - libXi.i686
  - libXtst
  - libXtst.i686
  - sysstat
  - unixODBC
  - unzip

kernel_params:
# Shared memory and semaphore /etc/sysctl.d/98-oracle.conf or /etc/sysctl.conf
- { name: fs.file-max, value: 6815744 }
- { name: kernel.sem, value: 250 32000 100 128 }
- { name: kernel.shmmni, value: 4096 }
- { name: kernel.shmall, value: 1073741824 }
- { name: kernel.shmmax, value: 4398046511104 }
- { name: kernel.panic_on_oops, value: 1 }
- { name: net.core.rmem_default, value: 262144 }
- { name: net.core.rmem_max, value: 4194304 }
- { name: net.core.wmem_default, value: 262144 }
- { name: net.core.wmem_max, value: 1048576 }
- { name: net.ipv4.conf.all.rp_filter, value: 2 }
- { name: net.ipv4.conf.default.rp_filter, value: 2 }
- { name: fs.aio-max-nr, value: 1048576 }
- { name: net.ipv4.ip_local_port_range, value: 9000 65500 }

# Oracle user shell limits
soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384
soft_stack: 10240
hard_stack: 32768
soft_memlock: 1887437
hard_memlock: 1887437

